### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by predy-dev** [predyprotocol/v2-contracts#4]
TODO

- [x] change poolId
- [x] use SafeCast
- [x] unrealized PnL use trade price
- [x] Update getter functions
- [x] limitPrice and deadline
- [x] use flash swap
* https://github.com/opynfinance/squeeth-monorepo/blob/main/packages/hardhat/contracts/strategy/base/StrategyFlashSwap.sol
- [x] fees
- [x] add comment to sqeeth scaling
- [x] Support BTC
- [x] getter of funding rate
- [x] protocol fee
- [x] available size (AMM depth)
- [x] 1 tx to approach multiple sub-vaults
- [x] onlyAdmin can update configs
- [x]  introduce minimum collateral and fix liquidation
- [x] change USDC event
- [ ] add ERC20 permit
- [x] liquidation reward is min(0.2 * MinCollateral, remain USDC)
